"""documents conversation link

Revision ID: 59ddc1fed5de
Revises: 8a36379753eb
Create Date: 2026-10-01 21:14:19.295256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ddc1fed5de'
down_revision: Union[str, Sequence[str], None] = '8a36379753eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_conversation_id'), 'documents', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_conversation_id'), table_name='documents')
    op.drop_column('documents', 'conversation_id')
    # ### end Alembic commands ###
